/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminPackage;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lenovo
 */
public class AfterLogin extends javax.swing.JFrame {

       public AfterLogin() {
          setContentPane(new JLabel(new ImageIcon("image3.jpg")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteNotificationButton = new javax.swing.JButton();
        addNotificationsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        deleteNotificationButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        deleteNotificationButton.setText("VIEW  NOTIFICATION");
        deleteNotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteNotificationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteNotificationButton);
        deleteNotificationButton.setBounds(240, 290, 390, 140);

        addNotificationsButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        addNotificationsButton.setText("ADD  NOTIFICATION");
        addNotificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNotificationsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNotificationsButton);
        addNotificationsButton.setBounds(10, 20, 390, 140);

        setSize(new java.awt.Dimension(801, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addNotificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNotificationsButtonActionPerformed
    notificationFrame show = new notificationFrame();
    show.setVisible(true);
    }//GEN-LAST:event_addNotificationsButtonActionPerformed

    private void deleteNotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteNotificationButtonActionPerformed
    NotificationShowFrame show = new NotificationShowFrame();
    show.setVisible(true);
    }//GEN-LAST:event_deleteNotificationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) 
   {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNotificationsButton;
    private javax.swing.JButton deleteNotificationButton;
    // End of variables declaration//GEN-END:variables
}
